{"errorMessage": "An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied", "errorType": "ClientError", "stackTrace": [["/var/task/reads3_python.py", 10, "lambda_handler", "response = s3.list_buckets()"], ["/var/runtime/botocore/client.py", 314, "_api_call", "return self._make_api_call(operation_name, kwargs)"], ["/var/runtime/botocore/client.py", 612, "_make_api_call", "raise error_class(parsed_response, operation_name)"]]}